version: "3.9"
services:
  docker-saigneur-config-server:
    image: saigneur-config-server
    container_name: msaigneur-config-server
    build:
      dockerfile: Dockerfile
    ports:
      - "9101:9101"
    restart: always
    networks:
      - saigneur-network

  docker-saigneur-postgres:
    image: postgis/postgis:14-3.3-alpine
    container_name: msaigneur-database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpostgres
    volumes:
      - /opt/saigneur_postgres_data:/var/lib/postgresql/data
    networks:
      - saigneur-network

networks:
  default:
    name: saigneur-network
#      external: true
