version: "3.9"
services:
  docker-saigneur-config-server:
    image: saigneur-config-server
    container_name: msaigneur-config-server
    build:
      dockerfile: Dockerfile
    ports:
      - "9101:9101"
    restart: always
    networks:
      - saigneur-network

  docker-saigneur-postgres:
    image: postgis/postgis:14-3.2
    container_name: msaigneur-database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpostgres
    networks:
      - saigneur-network

networks:
  saigneur-network: {}
